name: Tests

on:
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Git
      run: |
        echo "Running on Windows"
        choco install git -y

    - name: Configure Git for Windows
      run: |
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "${{ secrets.GH_USERNAME }}"
        git config --global credential.helper store

        # Create _netrc file for authentication
        echo machine github.com login x-access-token password ${{ secrets.GH_TOKEN }} > $HOME/_netrc
        echo machine api.github.com login x-access-token password ${{ secrets.GH_TOKEN }} >> $HOME/_netrc

        # Ensure correct line endings
        unix2dos $HOME/_netrc || echo "unix2dos not needed"

        # Set correct permissions
        git config --global core.askpass ""
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Debug Git authentication
      run: |
        git config --list
        git remote -v
        git status

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and generate report
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        pytest -n 1 --html=report.html --self-contained-html --log-cli-level=INFO

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report-${{ github.run_id }}-windows
        path: report.html
