name: Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python for ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run tests in parallel and generate report
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
      run: |
        pytest -n auto --html=report.html --self-contained-html --log-cli-level=INFO

    - name: Upload/save test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.html
