name: Tests

on:
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Git
      run: |
        echo "Running on Linux"
        sudo apt-get update
        sudo apt-get install -y git

    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "${{ secrets.GH_USERNAME }}"
        git config --global credential.helper store
        echo "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
        chmod 600 ~/.git-credentials
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Verify Git installation
      run: git --version

    - name: Verify Git configuration
      run: |
        git config --list
        git remote -v

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug environment
      run: |
        echo "Current working directory: $(pwd)"
        echo "Home directory: $HOME"
        ls -la
        ls -la $HOME
        git status

    - name: Run tests in parallel and generate report
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
      run: |
        pytest -n 1 --html=report.html --self-contained-html --log-cli-level=INFO

    - name: Upload/save test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report-${{ github.run_id }}-ubuntu-${{ matrix.python-version }}
        path: report.html

  test-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.13]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Git
      run: |
        echo "Running on Windows"
        choco install git -y

    - name: Configure Git
      run: |
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "${{ secrets.GH_USERNAME }}"
        git config --global credential.helper wincred
        echo "https://x-access-token:${{ secrets.GH_TOKEN }}@github.com" > $HOME/_netrc
        git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Verify Git installation
      run: git --version

    - name: Verify Git configuration
      run: |
        git config --list
        git remote -v
        git status

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests in parallel and generate report
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
      run: |
        pytest -n 1 --html=report.html --self-contained-html --log-cli-level=INFO

    - name: Upload/save test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report-${{ github.run_id }}-windows-${{ matrix.python-version }}
        path: report.html
