name: Tests

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      GH_EMAIL: ${{ secrets.GH_EMAIL }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
    - name: Set up Git config for all jobs
      run: |
        git config --global user.email "${{ secrets.GH_EMAIL }}"
        git config --global user.name "${{ secrets.GH_USERNAME }}"
        git config --global credential.helper store
        git config --global core.askpass ""
        echo machine github.com login x-access-token password ${{ secrets.GH_TOKEN }} > $HOME/.netrc
        echo machine api.github.com login x-access-token password ${{ secrets.GH_TOKEN }} >> $HOME/.netrc
        chmod 600 $HOME/.netrc

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.13]
    
    needs: setup

    env:
      GH_EMAIL: ${{ needs.setup.outputs.GH_EMAIL }}
      GH_USERNAME: ${{ needs.setup.outputs.GH_USERNAME }}
      GH_TOKEN: ${{ needs.setup.outputs.GH_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests and generate report
      run: |
        pytest -n 1 --html=report.html --self-contained-html --log-cli-level=INFO

    - name: Upload test report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-report-${{ github.run_id }}-${{ matrix.os }}
        path: report.html
